# Generated by Django 5.1.4 on 2025-01-16 09:06

import django_icon_picker.field
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExampleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", django_icon_picker.field.IconField(max_length=255)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
